

POST  http://127.0.0.1:8000/jwtoken/refresh/
Content-Type: application/json

{"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoic"}


###

POST http://127.0.0.1:8000/sales/api/sales/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5OTQ3NzQ0LCJpYXQiOjE3MTk5NDU5NDQsImp0aSI6IjBmMmMzMjM4ZmMwMDQ5OTNhMzljNjY4YzViODhmZTAxIiwidXNlcl9pZCI6MTl9.Sa5otakKbvSROtXBAiYIkptyq_ZFZXDVeQV1pQ8Ajek

{
    "customer": 2,
    "item": 2,
    "amount": 100.00,
    "quantity": 2,
    "status": "P"
}

###

POST https://flobooks.pythonanywhere.com/sales/api/sales/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyMDIyNjg4LCJpYXQiOjE3MjIwMTkwODgsImp0aSI6IjQxOGY5NTJlZjhmYjRlMDZhMmNkNzI2OGI5MDZmYzMzIiwidXNlcl9pZCI6ODF9.viQlhskAeNqvkktuDOD1pVN_ap65cdZyGzI4clAojTc

{
    "customer": 2,
    "item": 2,
    "amount": 100.00,
    "quantity": 2,
    "status": "P"
}
###


POST http://127.0.0.1:8000/sales/api/items/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5OTQ3NzQ0LCJpYXQiOjE3MTk5NDU5NDQsImp0aSI6IjBmMmMzMjM4ZmMwMDQ5OTNhMzljNjY4YzViODhmZTAxIiwidXNlcl9pZCI6MTl9.Sa5otakKbvSROtXBAiYIkptyq_ZFZXDVeQV1pQ8Ajek

{
    "name": "Okro Seed",
    "price": 20.00
}


###
POST http://127.0.0.1:8000/sales/api/customer/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5ODk1NzcyLCJpYXQiOjE3MTk4OTI2NDcsImp0aSI6IjkwYTRlMDMyMWYyNDQwNTk4N2JmZDNiM2M1YzA3NDc3IiwidXNlcl9pZCI6MTl9.Cau0FgGnEDqJJQ7149uY5WKnVlY8JMfCBs2HcFHD__w

{
    "name": "sam smith",
    "phoneNumber": "123456"
}

