GET  http://127.0.0.1:8000/gettoken/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MjI0ODc2LCJpYXQiOjE3MTgyMjQyMjEsImp0aSI6IjliMzA4Y2RiNzljMDQzNjhiZTQzNDZhMTM1M2I2MzJkIiwidXNlcl9pZCI6MTl9.q6rRj8TLar4Vdpt5N5FlKRf4e9QNdc4_A9W42fn4y4E
###

POST  http://127.0.0.1:8000/jwtoken/refresh/
Content-Type: application/json

{"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxODMxMDYyMSwiaWF0IjoxNzE4MjI0MjIxLCJqdGkiOiI0MDg0OTAzNDQ3ZjQ0NGZhOWQ4MDAyYmI3OTg4Zjg5NSIsInVzZXJfaWQiOjE5fQ.ybVKA9dCIYKLhc-aRhc3aCmPBfZnM8VUcUAkM8jgalI"}


###
GET  http://127.0.0.1:8000/manageaccounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MjI4NjcyLCJpYXQiOjE3MTgyMjQyMjEsImp0aSI6Ijc5MWRmYjI2NzEzNjQ3YWE4ZGUxMTRhNzRkYjg2ODZiIiwidXNlcl9pZCI6MTl9.6aLKXBATXFj5meaOcQkLibos59KOtPv9I_6cJe8HKQk
###

POST http://127.0.0.1:8000/manageaccounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MjI3MzcwLCJpYXQiOjE3MTgyMjQyMjEsImp0aSI6IjA5ZjMyMDU0M2Q0NjRlNWM5ZjliYjMxODVmYzVmNGVmIiwidXNlcl9pZCI6MTl9.6ta-hJcxWLkOH8ElT0mnn7cUIYYAxFuecNLfoOSH16k
X-CSRFToken: 323BNJbLYzFvgiapzvL1LdzCfEPKOfzeY6NLKR37Hnr6VBkRXFyBe4mvwX4B7IuN

{
"subuser_name" : "eto david",
  "subuser_email": "etodavid9@email.com",
  "subuser_password": "12345"
}
###

PUT http://127.0.0.1:8000/manageaccounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MjI4Mjk2LCJpYXQiOjE3MTgyMjQyMjEsImp0aSI6IjVhZmY5OGFjYjZlOTQ2NzRiZmM5MWQ1MDk5NTBiYzcyIiwidXNlcl9pZCI6MTl9.VC8npWP06THmPsIyH5G_h6wkdeNsZLehQMPLlWeofeo
X-CSRFToken: 323BNJbLYzFvgiapzvL1LdzCfEPKOfzeY6NLKR37Hnr6VBkRXFyBe4mvwX4B7IuN

{
"subuser_email": "etodavid9@email.com",
"subuser_name":"changed changed",
"subuser_password":"changed"
}

###

DELETE  loalhost/manageaccounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MjI4Mjk2LCJpYXQiOjE3MTgyMjQyMjEsImp0aSI6IjVhZmY5OGFjYjZlOTQ2NzRiZmM5MWQ1MDk5NTBiYzcyIiwidXNlcl9pZCI6MTl9.VC8npWP06THmPsIyH5G_h6wkdeNsZLehQMPLlWeofeo
X-CSRFToken: 323BNJbLYzFvgiapzvL1LdzCfEPKOfzeY6NLKR37Hnr6VBkRXFyBe4mvwX4B7IuN

{
"email": "etodavid9@email.com"

}

