
//to get the csrf token

GET  https://flobooks.pythonanywhere.com/gettoken/
Content-Type: application/json


###

//to signup

POST https://flobooks.pythonanywhere.com/signup/
Content-Type: application/json
X-CSRFToken: v0qTvMl9u6PGIxniLWCRx7FQtZfysdKQiiLIfli9IHLznCAxYdqxnguW7PC2D0a0
Referer: https://flobooks.pythonanywhere.com/signup/

{
                      "password": "1234",
                      "first_name": "ldfklj",
                      "last_name": "eldnfl",
                      "email": "test11@gmail.com",
                      "country": "lkdjf",
                      "state": "lkdjf",
                      "phoneNumber": "lkdjf",
                      "businessName": "lkdjf",
                      "businessAddress": "lkdjf",
                      "present_package": "lkdjf"
                    }

###

//to log in

POST https://flobooks.pythonanywhere.com/login/
Content-Type: application/json
X-CSRFToken: 2J9VPb9IOGIXzzG7Gz4Pj8vLfdkr3hnllO2Hj9MjEETVcY1nfGHqWU71lWyWiiRH
Referer: https://flobooks.pythonanywhere.com/signup/


{  "password": "1234", "email": "test11@gmail.com"  }

###

POST  https://flobooks.pythonanywhere.com/logout/
Content-Type: application/json
X-CSRFToken: kRLxAwDSECJFIBPqVnILhmb2FWvAc6f0HPTEQXqwgbre6LrC3YYBrqyhbSr0XGit
Authorization: Token 023396310e2eb314a297f08ccc5ff7237bb7ea3a


###

GET https://flobooks.pythonanywhere.com/dashboardmetadata/
Content-Type: application/json
Authorization: Token 023396310e2eb314a297f08ccc5ff7237bb7ea3a

###


POST  https://flobooks.pythonanywhere.com/uploadlogo/
Content-Type: application/json
X-CSRFToken: kRLxAwDSECJFIBPqVnILhmb2FWvAc6f0HPTEQXqwgbre6LrC3YYBrqyhbSr0XGit

{



  "business_logo" :
}

###

POST https://flobooks.pythonanywhere.com/uploadlogo/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="example.png"
Content-Type: image/png

[RAW PHOTO DATA HERE]
----WebKitFormBoundary7MA4YWxkTrZu0gW--



###

