# Generated by Django 5.0.4 on 2024-05-23 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subuser_name', models.CharField(default=' ', max_length=40)),
                ('subuser_email', models.EmailField(max_length=254, unique=True)),
                ('subuser_password', models.CharField(max_length=25)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
