# Generated by Django 5.0.4 on 2024-07-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageaccounts', '0002_remove_subuser_subuser_password_subuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='subuser_password',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
