# Generated by Django 5.0.4 on 2024-07-30 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageaccounts', '0003_subuser_subuser_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='subuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='subuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='subuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='subuser',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_auth_token', to='manageaccounts.subuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_auth_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subuser')},
            },
        ),
    ]
