
STATE_URLS = {
   "abia" : "https://abia.tax/",
"adamawa":"https://www.etax-adirs.net/",
 "akwa-ibom":"https://akirs.ibomtax.ng/",
  "anambra": "https://tax.services.an.gov.ng/",
  "bauchi": "http://www.mytax.birs.bu.gov.ng/",
  "bayelsa": "https://www.bir.by.gov.ng/",
  "benue": "https://birs.be.gov.ng/tax/tax-payers",
  "borno": "https://birs.bo.gov.ng/home/remita.php",
  "cross-river": "https://pay.crossriverstate.gov.ng/pay",
  "delta": "https://payment.deltabir.com/",
  "ebonyi": "https://irs.ebsgov.org/pay-tax",
  "edo": "https://login.remita.net/remita/edoirs/paywithaccount.re",
  "ekiti": "https://www.ekitistaterevenue.com/taxexplain.php",
  "enugu": "https://irs.en.gov.ng/home",
  "gombe": "https://giras.irs.gm.gov.ng/",
  "imo": "https://www.imostate.tax/",
  "jigawa": "https://login.remita.net/remita/external/FIRS/collector/payments.reg",
  "kaduna": "https://taxpayer-kadirs.aoctms.com.ng/",
  "kano": "https://login.remita.net/remita/external/FIRS/collector/payments.reg",
  "katsina": "https://revenue.katsinastate.gov.ng/landing/citizens/pay_bill",
  "kebbi": "https://irs.kb.gov.ng/etax/",
  "kogi": "https://etax.irs.kg.gov.ng",
  "kwara": ",https://forms.irs.kw.gov.ng/",
  "lagos": " https://etax.lirs.net",
  "nasarawa": "https://nasarawaigr.com/",
 "niger": "https://nigerigr.com/" ,
  "ogun": "https://portal.ogetax.ogunstate.gov.ng/",
  "ondo": "https://www.odirs.ng/index.php",
  "osun": "https://irs.os.gov.ng/" ,
  "oyo": "https://payment.oyostatebir.com/",
  "plateau":  "payment made in person",
  "rivers": ",https://rivtamis.riversbirs.gov.ng/",
  "sokoto": "https://itas.irs.sk.gov.ng/pay-tax",
  "taraba": "https://www.tarababir.gov.ng/",
  "yobe": "no official IRS e-payment site",
  "zamfara": "https://zirs.zm.gov.ng/home/knowledgebase.php?nid=E-PAYMENT",
"fct": "https://fctirs.gov.ng/",

}
