# Generated by Django 5.0.4 on 2024-09-10 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0003_item_date_registered"),
    ]

    operations = [
        migrations.CreateModel(
            name="VATTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_vat",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VAT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=7.5, max_digits=5),
                ),
                ("vat_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.sale"
                    ),
                ),
            ],
        ),
    ]
