# Generated by Django 5.0.4 on 2024-11-11 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commencement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vat_due', models.BooleanField(default=False)),
            ],
        ),
    ]
