# Generated by Django 5.0.4 on 2024-09-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vat",
            name="vat_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="vat",
            name="vat_rate",
            field=models.FloatField(default=7.5),
        ),
        migrations.AlterField(
            model_name="vattracker",
            name="total_vat",
            field=models.FloatField(default=0.0),
        ),
    ]
