# Generated by Django 5.0.4 on 2024-09-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0002_alter_vat_vat_amount_alter_vat_vat_rate_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VATTracker",
        ),
        migrations.RemoveField(
            model_name="vat",
            name="sale",
        ),
        migrations.RemoveField(
            model_name="vat",
            name="vat_amount",
        ),
        migrations.RemoveField(
            model_name="vat",
            name="vat_rate",
        ),
        migrations.AddField(
            model_name="vat",
            name="total_vat",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
