# Generated by Django 5.0.4 on 2024-09-10 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0003_delete_vattracker_remove_vat_sale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vat",
            name="commencement_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vat",
            name="vat_due",
            field=models.BooleanField(default=False),
        ),
    ]
