# Generated by Django 5.0.4 on 2024-11-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_customuser_start_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='onboarding/profile_photos'),
        ),
    ]
