# Generated by Django 5.0.4 on 2024-05-21 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subuser_email', models.EmailField(max_length=254, unique=True)),
                ('subuser_password', models.CharField(max_length=25)),
                ('subuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
