# Generated by Django 5.0.4 on 2024-05-21 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_subuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='subuser',
        ),
        migrations.AddField(
            model_name='subuser',
            name='base_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subuser',
            name='subuser_name',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
