# Generated by Django 5.0.4 on 2024-05-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_userphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subuser',
        ),
    ]
