# Generated by Django 5.0.4 on 2024-08-07 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_item_name_per_user"
            ),
        ),
    ]
