# Generated by Django 5.0.4 on 2024-09-02 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_item_unique_item_name_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date_registered",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
