# Generated by Django 5.0.4 on 2024-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_item_date_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
    ]
