# Generated by Django 5.0.4 on 2024-10-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_customer_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="sale",
        ),
        migrations.AddField(
            model_name="invoice",
            name="sales",
            field=models.ManyToManyField(to="sales.sale"),
        ),
    ]
