# Generated by Django 5.0.4 on 2024-11-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_rename_amount_due_accountsreceivable_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="dealers_name",
            field=models.CharField(default="", max_length=120),
        ),
    ]
