<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-11-09 04:40
=======
# Generated by Django 5.0.4 on 2024-11-09 04:45
>>>>>>> 27c158ea5a8e960a961636eb1c3b792e8a1b4ade

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('sales', '0007_rename_amount_due_accountsreceivable_amount_and_more'),
=======
        ("sales", "0007_rename_amount_due_accountsreceivable_amount_and_more"),
>>>>>>> 27c158ea5a8e960a961636eb1c3b792e8a1b4ade
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='purchase',
            name='dealers_name',
            field=models.CharField(default='', max_length=120),
=======
            model_name="purchase",
            name="dealers_name",
            field=models.CharField(default="", max_length=120),
>>>>>>> 27c158ea5a8e960a961636eb1c3b792e8a1b4ade
        ),
    ]
