# Generated by Django 5.0.4 on 2024-11-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_purchase_dealers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
